[colors.bright]
black = "#6272a4"
blue = "#80bfff"
cyan = "#8be9fd"
green = "#50fa7b"
magenta = "#ff79c6"
red = "#ff5555"
white = "#ffffff"
yellow = "#f1fa8c"

[colors.cursor]
cursor = "#f8f8f2"
text = "#282a36"

[colors.normal]
black = "#282a36"
blue = "#80bfff"
cyan = "#8be9fd"
green = "#50fa7b"
magenta = "#ff79c6"
red = "#ff5555"
white = "#f8f8f2"
yellow = "#f1fa8c"

[colors.primary]
background = "#282a36"
bright_foreground = "#ffffff"
foreground = "#f8f8f2"

[colors.selection]
background = "#44475a"
text = "#f8f8f2"

[font]
size = 10
[font.normal]
family = "Cascadia Mono"
style = "Regular"

[general]
import = ["$FLAKE/otherConfigs/alacritty/dracula.toml"]

[window]
opacity = 1.0
